### ISSUE TITLE
Can't clone the repo, missingSpaceBeforeDate

### ISSUE THREAD

**Issue by schwern** [pjf/ipc-system-simple#20]
```
$ git clone git@github.com:pjf/ipc-system-simple.git
Cloning into 'ipc-system-simple'...
remote: Counting objects: 1397, done.
error: object 15e5d148b97530edfce26f0542aa043f917a5ae6: missingSpaceBeforeDate: invalid author/committer line - missing space before date
fatal: Error in object
fatal: index-pack failed

$ git --version
git version 2.9.2
```

There's a way to fix it at the bottom of https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History You should be able to use `git cat-file -p 15e5d148` to find the offending name/email.

**Comment by jkeenan** [comment]
> ```
> $ git clone git@github.com:pjf/ipc-system-simple.git
> Cloning into 'ipc-system-simple'...
> remote: Counting objects: 1397, done.
> error: object 15e5d148b97530edfce26f0542aa043f917a5ae6: missingSpaceBeforeDate: invalid author/committer line - missing space before date
> fatal: Error in object
> fatal: index-pack failed
> 

In the course of performing co-maintenance on this distro in recent days I have had occasion to perform a `git clone` several times.  I have not experienced the problem in question.

I am self-assigning this ticket for the purpose of closing it in approx. 7 days unless I hear otherwise.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > ```
> > $ git clone git@github.com:pjf/ipc-system-simple.git
> > Cloning into 'ipc-system-simple'...
> > remote: Counting objects: 1397, done.
> > error: object 15e5d148b97530edfce26f0542aa043f917a5ae6: missingSpaceBeforeDate: invalid author/committer line - missing space before date
> > fatal: Error in object
> > fatal: index-pack failed
> > ```
> 
> In the course of performing co-maintenance on this distro in recent days I have had occasion to perform a `git clone` several times. I have not experienced the problem in question.
> 
> I am self-assigning this ticket for the purpose of closing it in approx. 7 days unless I hear otherwise.
> 
> Thank you very much.
> Jim Keenan

Closing as per prior post.
