### ISSUE TITLE
t/08_core.t fails, due to different die message

### ISSUE THREAD

**Issue by karenetheridge** [pjf/ipc-system-simple#23]
```
1..3
ok 1 - use IPC::System::Simple;
ok 2 - Signal caught,   $? = 6
not ok 3 - Coredump caught, $? = 6
#   Failed test 'Coredump caught, $? = 6'
#   at t/08_core.t line 51.
#                   '"/usr/bin/perl" died to signal "ABRT" (6) at t/08_core.t line 47.
# '
#     doesn't match '(?^:dumped core)'
# Looks like you failed 1 test of 3.
```
    This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi

`uname -a` says: `Linux vagrant-sandbox 3.2.0-101-generic #141-Ubuntu SMP Thu Mar 10 21:43:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Let me know if I can provide more info or help diagnose further.

**Comment by jkeenan** [comment]
Additional CPANtesters reports of this problem:
http://www.cpantesters.org/cpan/report/758b5294-3a33-11ea-90e5-674a1f24ea8f (ISS version 1.25, perl-5.8.9)
http://www.cpantesters.org/cpan/report/fa0ba5f6-3e74-11ea-9eba-37761f24ea8f (ISS version 1.26-TRIAL, perl-5.8.9)

**Comment by jkeenan** [comment]
I'm somewhat stumped on this intermittent test failure in IPC-System-Simple t/08_core.t.  I can't locate the source of the error message:  *died to signal "ABRT"*.  That syntax -- "died to" -- is not standard English but so far my DDG search hasn't turned anything up.

**Comment by karenetheridge** [comment]
https://metacpan.org/release/IPC-System-Simple/source/lib/IPC/System/Simple.pm#L62

**Comment by jkeenan** [comment]
> https://metacpan.org/release/IPC-System-Simple/source/lib/IPC/System/Simple.pm#L62

Thanks.  I think the problem here is not mainly in IPC::System::Simple but in perl-5.8.9.  See posting on perl5-porters list.

**Comment by jkeenan** [comment]
OTOH, here is a CPANtesters report for IPC-System-Simple v1.26 on Linux against perl-5.8.9 wherein t/08 is not skipped (due to absence of BSD::Resource) and which gets PASS.

http://www.cpantesters.org/cpan/report/b49a4f66-3f52-11ea-8e53-d4801f24ea8f

**Comment by jkeenan** [comment]
> > https://metacpan.org/release/IPC-System-Simple/source/lib/IPC/System/Simple.pm#L62
> 
> Thanks. I think the problem here is not mainly in IPC::System::Simple but in perl-5.8.9. See posting on perl5-porters list.

To which posting Zefram replied [here](https://www.nntp.perl.org/group/perl.perl5.porters/2020/01/msg256942.html).

**Comment by eserte** [comment]
So would the following diff fix the problem? (it does on my debian/stretch smoker with perl 5.8.9 installed)
```
diff --git a/lib/IPC/System/Simple.pm b/lib/IPC/System/Simple.pm
index 52ef556..ad71047 100644
--- a/lib/IPC/System/Simple.pm
+++ b/lib/IPC/System/Simple.pm
@@ -531,13 +531,13 @@ sub _process_child_error {
 
        my $coredump = WCOREDUMP($child_error);
 
-        # There's a bug in perl 5.10.0 where if the system
+        # There's a bug in perl 5.8.9 and 5.10.0 where if the system
         # does not provide a native WCOREDUMP, then $? will
         # never contain coredump information.  This code
         # checks to see if we have the bug, and works around
         # it if needed.
 
-        if ($] >= 5.010 and not $NATIVE_WCOREDUMP) {
+        if ($] >= 5.008009 and not $NATIVE_WCOREDUMP) {
             $coredump ||= WCOREDUMP( ${^CHILD_ERROR_NATIVE} );
         }
 
```

**Comment by jkeenan** [comment]
Works for me!  Now part of CPAN version 1.29, hot off the keyboard.

Thanks again.
Jim Keenan
